[platformio]
default_envs = test-host

[env:test-host]
platform = native
test_framework = unity
test_build_src = yes
lib_ldf_mode = deep

build_flags =
    -std=c++11
    -Iinclude
    -Isrc
    -Ilib/ArduinoHost

lib_extra_dirs = src

test_filter =
    test_main
    test_logger
    test_wifi_storage
    test_bt_commands
